version: '3'
services:
  app:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - GOOGLE_AI_KEY=${GOOGLE_AI_KEY}
      - KEY_FILE_NAME=${KEY_FILE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_DEVELOPMENT=${DB_DATABASE_DEVELOPMENT}
      - DB_DATABASE_PRODUCTION=${DB_DATABASE_PRODUCTION}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_DIALECT=${DB_DIALECT}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_DEVELOPMENT}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
